### PR TITLE
1.9.0 with linear_operator

### PR DESCRIPTION
**Pull request by AdrianSosic**
- Bump version to 1.9.0
- Add new dependency `linear_operator`

Hi @ngam , I've added the additional dependency. Anything else needed?

closes #24

### CODE REVIEW

**Comment by ngam** [comment]
linear_operator needs to be added to conda-forge, via staged-recipes https://github.com/conda-forge/staged-recipes

How interested are you in this?

**Comment by AdrianSosic** [comment]
HI @ngam, I've tried to add the corresponding recipe [here](https://github.com/conda-forge/staged-recipes/pull/20344). Could you please a look?

**Comment by ngam** [comment]
@conda-forge-admin please rerender

**Comment by ngam** [comment]
Thanks @AdrianSosic and welcome to conda-forge!!! 🥳 💚 🚀

**Comment by ngam** [comment]
needs https://github.com/conda-forge/linear_operator-feedstock/pull/1

**Pull request merged**
